DROP SEQUENCE SEQ_ID_USER;
DROP SEQUENCE SEQ_ID_BOOK;
DROP SEQUENCE SEQ_ID_PURCHASE;
DROP SEQUENCE SEQ_ID_ORDER;

DROP TABLE USERS 		CASCADE CONSTRAINTS PURGE;
DROP TABLE BOOK        	CASCADE CONSTRAINTS PURGE;
DROP TABLE PURCHASE    	CASCADE CONSTRAINTS PURGE;
DROP TABLE ORDERS    	CASCADE CONSTRAINTS PURGE;

CREATE SEQUENCE SEQ_ID_USER      	START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ID_BOOK       	START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ID_PURCHASE     START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ID_ORDER 		START WITH 1 INCREMENT BY 1;

CREATE TABLE USERS (IDUSER   NUMBER       CHECK (IDUSER > 0),
                     USERNAME   VARCHAR(100) NOT NULL,
                     FIRSTNAME  VARCHAR(100) NOT NULL,
                     LASTNAME   VARCHAR(100) NOT NULL,
                     ADRESSE		VARCHAR(100) NOT NULL,      
                     CONSTRAINT PK_USER    PRIMARY KEY (IDUSER));

CREATE TABLE BOOK (IDBOOK         	NUMBER       CHECK (IDBOOK > 0),
                    TITLE           VARCHAR(100) NOT NULL,
                    ISBN     		VARCHAR(100) NOT NULL,
                    AUTHOR          VARCHAR(100) NOT NULL,
                    PRICE           NUMBER    NOT NULL,
                    CATEGORY		VARCHAR(100) NOT NULL,
                    CONSTRAINT      PK_BOOK     PRIMARY KEY (IDBOOK));

CREATE TABLE PURCHASE (IDPURCHASE     NUMBER     CHECK (IDPURCHASE > 0),
                   IDUSER   NUMBER     CHECK (IDUSER > 0),
                   IDBOOK    NUMBER     CHECK (IDBOOK > 0),
                   PURCHASEDate   TIMESTAMP,
                   CONSTRAINT PK_PURCHASE PRIMARY KEY (IDPURCHASE),
                   CONSTRAINT PK_PURCHASE_USER    FOREIGN KEY (IDUSER) 	REFERENCES USERS (IDUSER)   ON DELETE CASCADE,
                   CONSTRAINT FK_PURCHASE_BOOK    FOREIGN KEY (IDBOOK)  REFERENCES BOOK (IDBOOK)   ON DELETE CASCADE);

CREATE TABLE ORDERS (IDORDER  NUMBER      CHECK (IDORDER > 0),
                          IDUSER         NUMBER     CHECK (IDUSER > 0),
                          IDBOOK         NUMBER     CHECK (IDBOOK > 0),
                          dateAdded		 TIMESTAMP,
                          CONSTRAINT      PK_ORDER  PRIMARY KEY (IDORDER),
                          CONSTRAINT FK_ORDER_USER    FOREIGN KEY (IDUSER) 	REFERENCES USERS (IDUSER)   ON DELETE CASCADE,
                   		  CONSTRAINT FK_ORDER_BOOK    FOREIGN KEY (IDBOOK)  REFERENCES BOOK (IDBOOK)   ON DELETE CASCADE);